export const API_PATHS = {
    SIGN_UP: 'auth/signup',
    LOGIN: 'auth/login',
    GET_ME: 'auth/get-me',
    DASHBOARD: 'dashboard',
    PETS: 'pets',
    PET: 'pet',
    CLIENTS: 'clients',
    CLIENT: 'clients/',
    SEARCH_CLIENTS: 'clients/search/',
    SEARCH_ONE_CLIENT: 'clients/search/one/',
    VISITS: 'visits',
    VISIT_PET: 'visits/pet/',
    LAST_VISIT: 'visits/last/',
    SEARCH_PETS: 'pets/search/',
    PETS_BY_CLIENT: 'pets/client/',
    CONDITIONS: 'conditions',
    PATHOLOGIES: 'pathologies',
};
