const common = {
    // primary: '#FD9340',
    primary: '#A765C1',
    primaryLight: '#D2C6EA',

    // secondary: '#2A2F4F',
    // tertiary: '#E5BEEC',
    quaternary: '#FDE2F3',
    white: '#FFFFFF',
    black: '#2F2F2F',
    blackSecondary: '#11100F',
    error: '#E74C3C',
    grey: '#EEEEEE',
    greySecondary: '#f5f5f5',
    greyDark: '#A3A3A3',
    greyDarkSecondary: '#616161',
    whatsapp: '#25d366',
    success: '#4E9F3D',
    teal: '#73B4B0',
    toastErrorLight: '#fdedef',
    toastSuccessLight: '#ebfbf5',
    toastWarningLight: '#fff9ea',
    toastDefaultLight: '#e5fafd',
    toastError: '#ef4d61',
    toastSuccess: '#3bd39d',
    toastWarning: '#fcc12f',
    toastDefault: '#36d0ea',
};

const light = {
    ...common,
    background: '#FFFFFF',
    text: '#11100F',
    secondary: '#2A2F4F',
    tertiary: '#E5BEEC',
    container: '#f5f4f6',
    separator: '#F1f1f2',
    border: '#2A2F4F',
    input: '#f2f1f6',
    textInput: '#515151',
    bottomSheet: '#F1f1f1',
    card: '#D6D6D6',
    backgroundInput: '#ECEDF0',
    backgroundContainer: '#DEDEDE',
    blue: '#092E9C',
    textButton: '#F1F1F1',
};

const dark = {
    ...common,
    background: '#131313',
    text: '#F1F1F1',
    tertiary: '#2A2F4F',
    secondary: '#E5BEEC',
    container: '#222125',
    separator: '#f0f0f0',
    border: '#E5BEEC',
    input: '#4C4C4C',
    textInput: '#DEDEDE',
    bottomSheet: '#4A4A4A',
    card: '#D6D6D6',
    backgroundInput: '#414141',
    backgroundContainer: '#B0B0B0',
    blue: '#2D5CE8',
    textButton: '#F1F1F1',
};

export const colors = { light, dark };

// selectedDayBackgroundColor: '#333248',
